name: "Resumenes de Futbol"
title: "Resumenes de Futbol"
tagline: "Un blog dedicado a informar spbre la ultimas noticas de la Premier, La Liga y el mundo del futbol"
description: "Resumenes de Futbol. Informacion actualizada sobre la premier league, la liga y otras competiciones. Resumenes de las ultimas jornadas, fichajes, quien es quien , curiosidades, y más!"
url: "http://resumenesdefutbol.com"
logo: 'avatar.png'


social:
  name: futbolresumen22
  links:
    - https://twitter.com/futbolresumen22
    - https://www.instagram.com/futbolresumen22

plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/


collections:
        about:
                output: true

excerpt_separator: '<!-- excerpt-end -->'
